#CS2705
#Network mapping with python
#Jared Anderson

import ipaddress

#Given address space is 138.191.0.0/16
#need to create 8 subnets
ipInterface = ipaddress.ip_interface('138.191.0.0/16')
ipNetwork = ipInterface.network

colleges = (list(ipaddress.ip_network(ipNetwork).subnets(prefixlen_diff=4)))

print('Valid host range: {0} - {1}'.format(((colleges[0].network_address)+1), (colleges[0].broadcast_address)-1))
print('\nApplied Science network address and subnet mask: ', colleges[0])
print('Arts & Humanities network address and subnet mask: ', colleges[1])
print('Education Science network address and subnet mask: ', colleges[2])
print('Business & Economics network address and subnet mask: ', colleges[3])
print('Health network address and subnet mask: ', colleges[4])
print('Science Science network address and subnet mask: ', colleges[5])
print('Social & Behavioral Science network address and subnet mask: ', colleges[6])
print('Information Technology network address and subnet mask: ', colleges[7])
print('Student Affairs network address and subnet mask: ', colleges[8])
print('Facilities Management network address and subnet mask: ', colleges[9])
print('Administrative Services network address and subnet mask: ', colleges[10])

ipInterface = ipaddress.ip_interface(colleges[0])
ipNetwork = ipInterface.network
east = (list(ipaddress.ip_network(ipNetwork).subnets(prefixlen_diff=3)))

print('\nSubnets within Applied Science:')
print('\nComputer Science network address and subnet mask: ', east[0])
print('Valid host range: {0} - {1}'.format(((east[0].network_address)+1), (east[0].broadcast_address)-1))
print('Professional Sales network address and subnet mask: ', east[1])
print('Valid host range: {0} - {1}'.format(((east[1].network_address)+1), (east[1].broadcast_address)-1))
print('Manufacturing Engineering  network address and subnet mask: ', east[2])
print('Valid host range: {0} - {1}'.format(((east[2].network_address)+1), (east[2].broadcast_address)-1))
print('Construction Management network address and subnet mask: ', east[3])
print('Valid host range: {0} - {1}'.format(((east[3].network_address)+1), (east[3].broadcast_address)-1))
print('Automotive Technology network address and subnet mask: ', east[4])
print('Valid host range: {0} - {1}'.format(((east[4].network_address)+1), (east[4].broadcast_address)-1))
print('Network Technology network address and subnet mask: ', east[5])
print('Valid host range: {0} - {1}'.format(((east[5].network_address)+1), (east[5].broadcast_address)-1))
print('Web Design network address and subnet mask: ', east[6])
print('Valid host range: {0} - {1}'.format(((east[6].network_address)+1), (east[6].broadcast_address)-1))
print('Engineering network address and subnet mask: ', east[7])
print('Valid host range: {0} - {1}'.format(((east[7].network_address)+1), (east[7].broadcast_address)-1))

ipInterface = ipaddress.ip_interface(colleges[1])
ipNetwork = ipInterface.network
east = (list(ipaddress.ip_network(ipNetwork).subnets(prefixlen_diff=3)))

print('\nSubnets within Arts & Humanities:')
print('\nKorean network address and subnet mask: ', east[0])
print('Valid host range: {0} - {1}'.format(((east[0].network_address)+1), (east[0].broadcast_address)-1))
print('German network address and subnet mask: ', east[1])
print('Valid host range: {0} - {1}'.format(((east[1].network_address)+1), (east[1].broadcast_address)-1))
print('Spanish network address and subnet mask: ', east[2])
print('Valid host range: {0} - {1}'.format(((east[2].network_address)+1), (east[2].broadcast_address)-1))
print('French network address and subnet mask: ', east[3])
print('Valid host range: {0} - {1}'.format(((east[3].network_address)+1), (east[3].broadcast_address)-1))
print('English network address and subnet mask: ', east[4])
print('Valid host range: {0} - {1}'.format(((east[4].network_address)+1), (east[4].broadcast_address)-1))
print('Visual Arts network address and subnet mask: ', east[5])
print('Valid host range: {0} - {1}'.format(((east[5].network_address)+1), (east[5].broadcast_address)-1))
print('Performing Arts network address and subnet mask: ', east[6])
print('Valid host range: {0} - {1}'.format(((east[6].network_address)+1), (east[6].broadcast_address)-1))
print('Communications  network address and subnet mask: ', colleges[7])
print('Valid host range: {0} - {1}'.format(((east[7].network_address)+1), (east[7].broadcast_address)-1))

ipInterface = ipaddress.ip_interface(colleges[2])
ipNetwork = ipInterface.network
east = (list(ipaddress.ip_network(ipNetwork).subnets(prefixlen_diff=3)))

print('\nSubnets within Education:')
print('\nChild and Family Studies network address and subnet mask: ', east[0])
print('Valid host range: {0} - {1}'.format(((east[0].network_address)+1), (east[0].broadcast_address)-1))
print('Health Promotion network address and subnet mask: ', east[1])
print('Valid host range: {0} - {1}'.format(((east[1].network_address)+1), (east[1].broadcast_address)-1))
print('Athletic Training network address and subnet mask: ', east[2])
print('Valid host range: {0} - {1}'.format(((east[2].network_address)+1), (east[2].broadcast_address)-1))
print('Human Performance network address and subnet mask: ', east[3])
print('Valid host range: {0} - {1}'.format(((east[3].network_address)+1), (east[3].broadcast_address)-1))
print('Teacher Education network address and subnet mask: ', east[4])
print('Valid host range: {0} - {1}'.format(((east[4].network_address)+1), (east[4].broadcast_address)-1))
print('Exercise Physiology network address and subnet mask: ', east[5])
print('Valid host range: {0} - {1}'.format(((east[5].network_address)+1), (east[5].broadcast_address)-1))
print('Health Education network address and subnet mask: ', east[6])
print('Valid host range: {0} - {1}'.format(((east[6].network_address)+1), (east[6].broadcast_address)-1))
print('Recreation Management  network address and subnet mask: ', colleges[7])
print('Valid host range: {0} - {1}'.format(((east[7].network_address)+1), (east[7].broadcast_address)-1))

ipInterface = ipaddress.ip_interface(colleges[3])
ipNetwork = ipInterface.network
east = (list(ipaddress.ip_network(ipNetwork).subnets(prefixlen_diff=3)))

print('\nSubnets within Business & Economics :')
print('\nBusiness Administration network address and subnet mask: ', east[0])
print('Valid host range: {0} - {1}'.format(((east[0].network_address)+1), (east[0].broadcast_address)-1))
print('Economics network address and subnet mask: ', east[1])
print('Valid host range: {0} - {1}'.format(((east[1].network_address)+1), (east[1].broadcast_address)-1))
print('Information Systems Tech network address and subnet mask: ', east[2])
print('Valid host range: {0} - {1}'.format(((east[2].network_address)+1), (east[2].broadcast_address)-1))
print('Master of Business Admin	 network address and subnet mask: ', east[3])
print('Valid host range: {0} - {1}'.format(((east[3].network_address)+1), (east[3].broadcast_address)-1))
print('Accounting network address and subnet mask: ', east[4])
print('Valid host range: {0} - {1}'.format(((east[4].network_address)+1), (east[4].broadcast_address)-1))
print('Business Education network address and subnet mask: ', east[5])
print('Valid host range: {0} - {1}'.format(((east[5].network_address)+1), (east[5].broadcast_address)-1))
print('Master of Accountancy network address and subnet mask: ', east[6])
print('Valid host range: {0} - {1}'.format(((east[6].network_address)+1), (east[6].broadcast_address)-1))
print('Master of Taxation network address and subnet mask: ', colleges[7])
print('Valid host range: {0} - {1}'.format(((east[7].network_address)+1), (east[7].broadcast_address)-1))

ipInterface = ipaddress.ip_interface(colleges[4])
ipNetwork = ipInterface.network
east = (list(ipaddress.ip_network(ipNetwork).subnets(prefixlen_diff=3)))

print('\nSubnets within Health:')
print('\nDental Hygiene network address and subnet mask: ', east[0])
print('Valid host range: {0} - {1}'.format(((east[0].network_address)+1), (east[0].broadcast_address)-1))
print('Emergency Care   network address and subnet mask: ', east[1])
print('Valid host range: {0} - {1}'.format(((east[1].network_address)+1), (east[1].broadcast_address)-1))
print('Health Information Mgmt network address and subnet mask: ', east[2])
print('Valid host range: {0} - {1}'.format(((east[2].network_address)+1), (east[2].broadcast_address)-1))
print('Nursing network address and subnet mask: ', east[3])
print('Valid host range: {0} - {1}'.format(((east[3].network_address)+1), (east[3].broadcast_address)-1))
print('Medical Laboratory address and subnet mask: ', east[4])
print('Valid host range: {0} - {1}'.format(((east[4].network_address)+1), (east[4].broadcast_address)-1))
print('Radiology network address and subnet mask: ', east[5])
print('Valid host range: {0} - {1}'.format(((east[5].network_address)+1), (east[5].broadcast_address)-1))
print('Respiratory Therapy network address and subnet mask: ', east[6])
print('Valid host range: {0} - {1}'.format(((east[6].network_address)+1), (east[6].broadcast_address)-1))
print('Occupational Therapy network address and subnet mask: ', colleges[7])
print('Valid host range: {0} - {1}'.format(((east[7].network_address)+1), (east[7].broadcast_address)-1))

ipInterface = ipaddress.ip_interface(colleges[5])
ipNetwork = ipInterface.network
east = (list(ipaddress.ip_network(ipNetwork).subnets(prefixlen_diff=3)))

print('\nSubnets within Science:')
print('\nBotany network address and subnet mask: ', east[0])
print('Valid host range: {0} - {1}'.format(((east[0].network_address)+1), (east[0].broadcast_address)-1))
print('Geosciences network address and subnet mask: ', east[1])
print('Valid host range: {0} - {1}'.format(((east[1].network_address)+1), (east[1].broadcast_address)-1))
print('Microbiology network address and subnet mask: ', east[2])
print('Valid host range: {0} - {1}'.format(((east[2].network_address)+1), (east[2].broadcast_address)-1))
print('Developmental Math address and subnet mask: ', east[3])
print('Valid host range: {0} - {1}'.format(((east[3].network_address)+1), (east[3].broadcast_address)-1))
print('Physics address and subnet mask: ', east[4])
print('Valid host range: {0} - {1}'.format(((east[4].network_address)+1), (east[4].broadcast_address)-1))
print('Zoology network address and subnet mask: ', east[5])
print('Valid host range: {0} - {1}'.format(((east[5].network_address)+1), (east[5].broadcast_address)-1))
print('Mathematics network address and subnet mask: ', east[6])
print('Valid host range: {0} - {1}'.format(((east[6].network_address)+1), (east[6].broadcast_address)-1))
print('Human Anatomy Physiology network address and subnet mask: ', colleges[7])
print('Valid host range: {0} - {1}'.format(((east[7].network_address)+1), (east[7].broadcast_address)-1))

ipInterface = ipaddress.ip_interface(colleges[6])
ipNetwork = ipInterface.network
east = (list(ipaddress.ip_network(ipNetwork).subnets(prefixlen_diff=3)))

print('\nSubnets within Social and Behavioral Science:')
print('\nCriminal Justice network address and subnet mask: ', east[0])
print('Valid host range: {0} - {1}'.format(((east[0].network_address)+1), (east[0].broadcast_address)-1))
print('Geography network address and subnet mask: ', east[1])
print('Valid host range: {0} - {1}'.format(((east[1].network_address)+1), (east[1].broadcast_address)-1))
print('History network address and subnet mask: ', east[2])
print('Valid host range: {0} - {1}'.format(((east[2].network_address)+1), (east[2].broadcast_address)-1))
print('Military Science Math network address and subnet mask: ', east[3])
print('Valid host range: {0} - {1}'.format(((east[3].network_address)+1), (east[3].broadcast_address)-1))
print('Philosophy & Poli Sci network address and subnet mask: ', east[4])
print('Valid host range: {0} - {1}'.format(((east[4].network_address)+1), (east[4].broadcast_address)-1))
print('Psychology network address and subnet mask: ', east[5])
print('Valid host range: {0} - {1}'.format(((east[5].network_address)+1), (east[5].broadcast_address)-1))
print('Social Work network address and subnet mask: ', east[6])
print('Valid host range: {0} - {1}'.format(((east[6].network_address)+1), (east[6].broadcast_address)-1))
print('Sociology & Anthropology network address and subnet mask: ', colleges[7])
print('Valid host range: {0} - {1}'.format(((east[7].network_address)+1), (east[7].broadcast_address)-1))

ipInterface = ipaddress.ip_interface(colleges[7])
ipNetwork = ipInterface.network
east = (list(ipaddress.ip_network(ipNetwork).subnets(prefixlen_diff=3)))

print('\nSubnets within Information Technology:')
print('\nComputing Support network address and subnet mask: ', east[0])
print('Valid host range: {0} - {1}'.format(((east[0].network_address)+1), (east[0].broadcast_address)-1))
print('Telecommunications  network address and subnet mask: ', east[1])
print('Valid host range: {0} - {1}'.format(((east[1].network_address)+1), (east[1].broadcast_address)-1))
print('Administrative Computing network address and subnet mask: ', east[2])
print('Valid host range: {0} - {1}'.format(((east[2].network_address)+1), (east[2].broadcast_address)-1))
print('Networking network address and subnet mask: ', east[3])
print('Valid host range: {0} - {1}'.format(((east[3].network_address)+1), (east[3].broadcast_address)-1))
print('Academic Computing network address and subnet mask: ', east[4])
print('Valid host range: {0} - {1}'.format(((east[4].network_address)+1), (east[4].broadcast_address)-1))
print('Computer Security network address and subnet mask: ', east[5])
print('Valid host range: {0} - {1}'.format(((east[5].network_address)+1), (east[5].broadcast_address)-1))
print('Database Administration network address and subnet mask: ', east[6])
print('Valid host range: {0} - {1}'.format(((east[6].network_address)+1), (east[6].broadcast_address)-1))
print('VP of IT Office network address and subnet mask: ', colleges[7])
print('Valid host range: {0} - {1}'.format(((east[7].network_address)+1), (east[7].broadcast_address)-1))

ipInterface = ipaddress.ip_interface(colleges[8])
ipNetwork = ipInterface.network
east = (list(ipaddress.ip_network(ipNetwork).subnets(prefixlen_diff=3)))

print('\nSubnets within Student Affairs:')
print('\nStudent Life network address and subnet mask: ', east[0])
print('Valid host range: {0} - {1}'.format(((east[0].network_address)+1), (east[0].broadcast_address)-1))
print('Student Services network address and subnet mask: ', east[1])
print('Valid host range: {0} - {1}'.format(((east[1].network_address)+1), (east[1].broadcast_address)-1))
print('Outreach network address and subnet mask: ', east[2])
print('Valid host range: {0} - {1}'.format(((east[2].network_address)+1), (east[2].broadcast_address)-1))
print('Academic Support network address and subnet mask: ', east[3])
print('Valid host range: {0} - {1}'.format(((east[3].network_address)+1), (east[3].broadcast_address)-1))
print('Focused Interest network address and subnet mask: ', east[4])
print('Valid host range: {0} - {1}'.format(((east[4].network_address)+1), (east[4].broadcast_address)-1))
print('Career Services network address and subnet mask: ', east[5])
print('Valid host range: {0} - {1}'.format(((east[5].network_address)+1), (east[5].broadcast_address)-1))
print('Veterans Affairs network address and subnet mask: ', east[6])
print('Valid host range: {0} - {1}'.format(((east[6].network_address)+1), (east[6].broadcast_address)-1))
print('Diversity network address and subnet mask: ', colleges[7])
print('Valid host range: {0} - {1}'.format(((east[7].network_address)+1), (east[7].broadcast_address)-1))

ipInterface = ipaddress.ip_interface(colleges[9])
ipNetwork = ipInterface.network
east = (list(ipaddress.ip_network(ipNetwork).subnets(prefixlen_diff=3)))

print('\nSubnets within Facilities Management:')
print('\nCampus planning  network address and subnet mask: ', east[0])
print('Valid host range: {0} - {1}'.format(((east[0].network_address)+1), (east[0].broadcast_address)-1))
print('Construction network address and subnet mask: ', east[1])
print('Valid host range: {0} - {1}'.format(((east[1].network_address)+1), (east[1].broadcast_address)-1))
print('Custodial network address and subnet mask: ', east[2])
print('Valid host range: {0} - {1}'.format(((east[2].network_address)+1), (east[2].broadcast_address)-1))
print('Landscaping network address and subnet mask: ', east[3])
print('Valid host range: {0} - {1}'.format(((east[3].network_address)+1), (east[3].broadcast_address)-1))
print('Electrical network address and subnet mask: ', east[4])
print('Valid host range: {0} - {1}'.format(((east[4].network_address)+1), (east[4].broadcast_address)-1))
print('Mechanical network address and subnet mask: ', east[5])
print('Valid host range: {0} - {1}'.format(((east[5].network_address)+1), (east[5].broadcast_address)-1))
print('Business Services network address and subnet mask: ', east[6])
print('Valid host range: {0} - {1}'.format(((east[6].network_address)+1), (east[6].broadcast_address)-1))
print('Parking Services address and subnet mask: ', colleges[7])
print('Valid host range: {0} - {1}'.format(((east[7].network_address)+1), (east[7].broadcast_address)-1))

ipInterface = ipaddress.ip_interface(colleges[10])
ipNetwork = ipInterface.network
east = (list(ipaddress.ip_network(ipNetwork).subnets(prefixlen_diff=3)))

print('\nSubnets within Administrative Services:')
print('\nAthletics network address and subnet mask: ', east[0])
print('Valid host range: {0} - {1}'.format(((east[0].network_address)+1), (east[0].broadcast_address)-1))
print('Accounting network address and subnet mask: ', east[1])
print('Valid host range: {0} - {1}'.format(((east[1].network_address)+1), (east[1].broadcast_address)-1))
print('Budget network address and subnet mask: ', east[2])
print('Valid host range: {0} - {1}'.format(((east[2].network_address)+1), (east[2].broadcast_address)-1))
print('Enviro Health & Safety network address and subnet mask: ', east[3])
print('Valid host range: {0} - {1}'.format(((east[3].network_address)+1), (east[3].broadcast_address)-1))
print('Printing network address and subnet mask: ', east[4])
print('Valid host range: {0} - {1}'.format(((east[4].network_address)+1), (east[4].broadcast_address)-1))
print('Human Resources network address and subnet mask: ', east[5])
print('Valid host range: {0} - {1}'.format(((east[5].network_address)+1), (east[5].broadcast_address)-1))
print('Purchasing network address and subnet mask: ', east[6])
print('Valid host range: {0} - {1}'.format(((east[6].network_address)+1), (east[6].broadcast_address)-1))
print('Police and Security network address and subnet mask: ', colleges[7])
print('Valid host range: {0} - {1}'.format(((east[7].network_address)+1), (east[7].broadcast_address)-1))